version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=127.0.0.1
      - FLASK_ENV=development
      - QWEN_API_KEY={QWEN_API_KEY}
    restart: unless-stopped
    container_name: english_essay_app
